### ISSUE TITLE
Missing Target Font...

### ISSUE THREAD

**Issue by jwinarske** [chinmaygarde/flutter_from_scratch#3]
I'm trying to run the flutter_gallery bundle on a Pi, and am hitting the below exception.  I'm using the [Engine master branch](https://github.com/flutter/engine), no changes.  Are you overriding debugDefaultTargetPlatformOverride in dart?

```
LOG: /home/joel/git/flutter_embedded/build/rpi_flutter-prefix/src/rpi_flutter/flutter/main.cc:66: Display Size: 800 x 480
flutter: Observatory listening on http://127.0.0.1:34745/
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown attaching to the render tree:
flutter: Unknown platform.
flutter: linux was not recognized as a target platform. Consider updating the list of TargetPlatforms to
flutter: include this platform.
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      defaultTargetPlatform (package:flutter/src/foundation/platform.dart:68:5)
flutter: #1      new ThemeData (package:flutter/src/material/theme_data.dart:206:18)
flutter: #2      new ThemeData.light (package:flutter/src/material/theme_data.dart:410:32)
flutter: #3      _buildLightTheme (package:flutter_gallery/gallery/themes.dart:59:36)
flutter: #4      kLightGalleryTheme (package:flutter_gallery/gallery/themes.dart:15:65)
flutter: #5      kLightGalleryTheme (package:flutter_gallery/gallery/themes.dart:15:20)
flutter: #6      _GalleryAppState.initState (package:flutter_gallery/gallery/app.dart:61:14)
flutter: #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #17     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #18     main (package:flutter_gallery/main.dart:13:3)
flutter: #19     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
```

**Comment by jwinarske** [comment]
This looks applicable:  [Flutter-Requirements](https://github.com/google/flutter-desktop-embedding/blob/master/Flutter-Requirements.md)

**Comment by jwinarske** [comment]
Re-worked flutter/packages/flutter/lib/src/foundation/platform.dart to check for Linux.  Then hit:

```
LOG: /home/joel/git/flutter_embedded/build/rpi_flutter-prefix/src/rpi_flutter/flutter/main.cc:66: Display Size: 800 x 480
flutter: Observatory listening on http://127.0.0.1:33609/
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown attaching to the render tree:
flutter: 'package:flutter/src/material/typography.dart': Failed assertion: line 121 pos 14: 'black != null':
flutter: is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Typography._ (package:flutter/src/material/typography.dart:121:14)
flutter: #3      new Typography (package:flutter/src/material/typography.dart:117:23)
flutter: #4      new ThemeData (package:flutter/src/material/theme_data.dart:207:20)
flutter: #5      new ThemeData.light (package:flutter/src/material/theme_data.dart:410:32)
flutter: #6      _buildLightTheme (package:flutter_gallery/gallery/themes.dart:59:36)
flutter: #7      kLightGalleryTheme (package:flutter_gallery/gallery/themes.dart:15:65)
flutter: #8      kLightGalleryTheme (package:flutter_gallery/gallery/themes.dart:15:20)
flutter: #9      _GalleryAppState.initState (package:flutter_gallery/gallery/app.dart:61:14)
flutter: #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #15     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #16     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #18     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #20     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #21     main (package:flutter_gallery/main.dart:13:3)
flutter: #22     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
```

**Comment by jwinarske** [comment]
Running hello_world, it's limited to:

```
LOG: /home/joel/git/flutter_embedded/build/rpi_flutter-prefix/src/rpi_flutter/flutter/main.cc:66: Display Size: 800 x 480
flutter: Observatory listening on http://127.0.0.1:36411/
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
```
Based on the failing call getFontTable(), it looks like there is a assumption on what Fonts are available.  Which looks very similar to the Font section of the Flutter-Requirements doc referenced above.  I'm suspecting I need to explicitly define/use Fonts, and make no assumption about what is available on the target.

**Comment by jwinarske** [comment]
I figured it out after single stepping through the engine.  

**Error call stack**
```
Thread #6 [io.flutter.ui] 3285 [core: 3] (Suspended : Step)	
	minikin::FontFamily::computeCoverage() at FontFamily.cpp:184 0x7635104a	
	minikin::FontFamily::FontFamily() at FontFamily.cpp:112 0x76350f86	
	minikin::FontFamily::FontFamily() at FontFamily.cpp:103 0x76350f86	
	minikin::FontFamily::FontFamily() at FontFamily.cpp:100 0x76350f86	
	std::__1::__compressed_pair_elem<minikin::FontFamily, 1, false>::__compressed_pair_elem<std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> >&&, 0u>() at memory:2,148 0x76359f24	
	std::__1::__compressed_pair<std::__1::allocator<minikin::FontFamily>, minikin::FontFamily>::__compressed_pair<std::__1::allocator<minikin::FontFamily>&, std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> >&&>() at memory:2,251 0x76359f24	
	std::__1::__shared_ptr_emplace<minikin::FontFamily, std::__1::allocator<minikin::FontFamily> >::__shared_ptr_emplace<std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> > >() at memory:3,664 0x76359f24	
	std::__1::shared_ptr<minikin::FontFamily>::make_shared<std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> > >() at memory:4,323 0x76359f24	
	std::__1::make_shared<minikin::FontFamily, std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> > >() at memory:4,702 0x76359f24	
	txt::FontCollection::CreateMinikinFontFamily() at font_collection.cc:224 0x76359f24	
	txt::FontCollection::FindFontFamilyInManagers() at font_collection.cc:186 0x76359cb2	
	txt::FontCollection::GetMinikinFontCollectionForFamilies() at font_collection.cc:141 0x763598fa	
	txt::Paragraph::GetMinikinFontCollectionForStyle() at paragraph.cc:906 0x7635cdea	
	txt::Paragraph::ComputeLineBreaks() at paragraph.cc:290 0x7635c9d8	
	txt::Paragraph::Layout() at paragraph.cc:435 0x7635d4a2	
	blink::Paragraph::layout() at paragraph.cc:80 0x763814a2	
	tonic::DartDispatcher<tonic::IndicesHolder<0u>, void (blink::Paragraph::*)(double)>::Dispatch at dart_args.h:151 0x763814a2	
	tonic::DartCall<void (blink::Paragraph::*)(double)> at dart_args.h:204 0x763814a2	
	blink::Paragraph_layout() at paragraph.cc:36 0x763814a2	
	dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck() at native_entry.cc:197 0x764d4aec	
	0x713c0888	
```

**Problems**
1.  The Skia font manager points to /usr/local/fonts.  See SkFontMgr::RefDefault() in src/third_party/skia/src/core/SkFontMgr.cpp.  /usr/local/fonts is missing from the Raspian Stretch Lite image.

2.  The default font for Linux is defined in src/flutter/third_party/txt/src/txt/platform.cc, which is selected in src/flutter/third_party/txt/BUILD.gn.  In the case of Linux the default font is Arial.ttf, as such you need an Arial.ttf in /usr/local/fonts.

**Solution**
On target (Raspberry Pi), create folder /usr/local/fonts, and copy Arial.ttf into it.
